version: '2'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    env_file: .env-prod
    command: ["prod"]
    networks:
      - internal
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: postgres
    env_file: .env-prod
    networks:
      - internal
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile.nginx
    labels:
      - traefik.backend=kanban-aio
      - traefik.frontend.rule=Host:strawpoll-be.aiotools.ovh
      - traefik.docker.network=proxy
      - traefik.port=9009
    networks:
      - internal
      - proxy
    links:
      - app:web
    depends_on:
        - app
    restart: always
volumes:
  postgresdata:
networks:
  proxy:
    external: true
  internal:
    external: false