version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - 9019:9009
    container_name: covid_app_dev
    env_file: .env-dev
    command: ["dev"]
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: postgres
    container_name: covid_postgres_dev
    env_file: .env-dev
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgresdata:

