version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    env_file: .env-test
    command: ["test"]
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: postgres
    container_name: covid_postgres_test
    env_file: .env-test
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata:

