
version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    env_file: .env-test
    command: ["test"]
    networks:
      - internal
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: postgres
    env_file: .env-test
    networks:
      - internal
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata:
      
      