version: '3'
services:
  frontend:
    image: webdevops/apache:latest
    volumes:
      - ./cordova/www/:/app
    labels:
      - traefik.frontend.rule=Host:strawpoll.aiotools.ovh
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
